### ISSUE TITLE
US 8: Create a new periotopia-index

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#10]
## Value proposition

As a user
I want to be able to start a new round of the questionnaire
So that I can play around and see what is changing if I were in a different situation

## Description

![Image](https://user-images.githubusercontent.com/132840529/253285931-07f42572-536b-4968-a4fb-2b3850fc73cd.png)

## Acceptance criteria

- [ ] The `overview` page has a button to add a new periotopia-index, stating "Erstelle einen neuen Periotopia-Index"
- [ ] When clicking the button you can start a new round of questions
- [ ] The results are being saved on the `overview` page 

## Tasks

- [ ] Add `button`on overview page
- [ ] Render result of new questionnaire-round on `overview` page

**Comment by AliaksandraNovikava** [comment]
Hey @tejue .
You US lgtm 👍

Just one small question: 
Do you need your second task in this US? You already have it in your US 6.

**Comment by tejue** [comment]
Hey Alex, thx for the review and the hint. I added a new wireframe so the difference to US6 is more clear. Thank you for the hint
