### ISSUE TITLE
US 9: Delete a questionnaire-result on overviewpage

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#11]
## Value proposition

As a user
I want to be able to delete a single periotopia-index
So that I can get rid of it in case I don't want to have it anoymore

## Description

![Image](https://user-images.githubusercontent.com/132840529/253288328-26c5e017-ee27-4411-8ec6-83d818be9d46.png)

## Acceptance criteria

- [ ] The overview page shows a button to delete a single periotopia-index
- [ ] When clicking the button an alert to confirm will show up 
- [ ] When confirming the single periotopia-index will be deleted

## Tasks

- [ ] Create a button to delete a periotopia-index
- [ ] Create function to delete the correct periotopia-index

**Comment by vaupunkt** [comment]
lgtm ⛵️
