### ISSUE TITLE
US 10: Create landing-page

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#17]
## Value proposition

As a user
I want to start on a landing page with some more information about the topic
So that I know more or less what the questionnaire is about and what to expect

As a user
I want to start on a landing page 
So that I know more or less what the app is about

## Description

![Image](https://user-images.githubusercontent.com/132840529/254918813-1a892719-fe4e-4819-87f8-ba635696fd25.png)

## Acceptance criteria

- [ ] The App has a landing-page
- [ ] The landingpage shows a link which leads to the overviewpage (rename: periotopia-index)
- [ ] The text for the landing page is: "Täglich menstruieren mindestens 300 Millionen Menschen* weltweit. Und obwohl die Menstruation unweigerlich mit der Existenz der Menschheit verbunden ist, ist sie noch immer ein riesiges Tabuthema - mit Folgen. In Periotopia, einer (peri)-utopischen Welt, wäre einiges anders... --> *Nicht alle Frauen menstruieren und nicht alle menstruierenden Menschen sind Frauen.  
- [ ] The Page has a Link displaying "Let's talk red"

## Tasks

- [ ] Create new branch
- [ ] Move overview to another page
- [ ] Rename overview to periotopia-index
- [ ] Create infoblock for landing page
- [ ] Implement a link leading to the overviewpage

**Comment by ekat-br** [comment]
Hi @tejue, nice user story! 

To better understand: On the landing page, there are two links. The first link leads to the Overview Page. The second link says "Let's talk red.". Where does the second link lead to?

**Comment by tejue** [comment]
Hi @ekat-br ,
The link is supposed to be one and the same: The text is "Let's talk red" and it leads to the overview page. For a better understanding I'll switch the sequence of the acceptance criteria. Thanks for the hint :)

**Comment by ekat-br** [comment]
Great🚀
