### ISSUE TITLE
US 11: Add changable name for each periotopia-index

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#18]
## Value proposition

As a user
I want to give my periotopia-indices different titles
So that I can better differentiate between my periotopia-indices

## Description

![Image](https://user-images.githubusercontent.com/132840529/254939552-2188012f-8a6b-47a7-8f6d-fb5d9d2a9744.png)

## Acceptance criteria

- [ ] The created indices have a field to put in individual title in and save it this way
- [ ] The given title is changeable
- [ ] When no title was given, the title "Dein Periotopia-Index" is used 

## Tasks

- [ ] Create a branch
- [ ] Create an inputfield to put a title in and save it
- [ ] Use "Dein Periotopia-Index as default-value
- [ ] Make the title changable

**Comment by tejue** [comment]
Hey @ekat-br,
thanks, you're totally right. I changed it and hope my developer can understand better now :)

**Comment by ekat-br** [comment]
Perfect🙌

**Comment by Roland-Hufnagel** [comment]
THis looks good to me 👍
