### ISSUE TITLE
US 12: Add styling

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#19]
## Value proposition

As a UX/UI-Designer
I want the app to look nice
So that the user enjoys using the app and has a good experience without being too distracted

## Description

The developer should also use her own sense of styling if she discovers that some other colors ore else would fit better 

![Image](https://user-images.githubusercontent.com/132840529/255100962-61e66992-1933-43b1-a99a-fdd4a5f09334.png)

## Acceptance criteria

- [ ] Background: fff7ff
- [ ] Boxes: e3005f, margin between, no margin to viewport
- [ ] Text/Icon on light background: 343a40
- [ ] Text/Icon on dark background: fff7ff
- [ ] Index filling: e60800
- [ ] Buttons and Links should not be blue on mobile devices
- [ ] The page has icons instead of buttons with text

## Tasks

- [ ] Create a new branch
- [ ] Add stylesheets
- [ ] Implement root-colors
- [ ] Implement root-margin/gaps

**Comment by Roland-Hufnagel** [comment]
Hi Teresa. In my opinion this is not a good userstory. Like the word 'userstory' tells it should have a value proposition for the 'user'. Only if it has a value for the user, there is a reason to develop something. Maybe it could sound like: 'As a user I want to have a very good UX-experience so that I enjoy using the app.' For me this sounds much better to give money for developing a great styling. (If your coach allowed you to write userstories from an UX-perspective forget my recommondations)

I recommend to remove this US completely. Because if the value is to have a good UX-experience then you have to do a really concrete good job in styling. Then it has to be perfectly styled. But only to give some instructions for some colors and margin is far away from perfect styling. In other Userstories you can add the task: 'add some basic styling' and then use these colors and margins, what you like (you don't have to define them that explicit in the story)

**Comment by tejue** [comment]
Hey @Roland-Hufnagel, 
thanks a lot for your feedback. I was not sure how to write this US at all. My whole app is a questionnaire and I figured I probably won't need that much styling (compared to other apps). So I will take this US out for now and implement styling into other US's. Thanks again
