### ISSUE TITLE
US 2: Show questions with corresponding answers for question-block 'financial issues'

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#2]
## Value proposition

As a user
I want to see the questions for 'financial issues' as well as answer possibilities
So that I know how much my menstruation costs me

## Description

![Image](https://user-images.githubusercontent.com/132840529/251366106-17baa352-b69c-4f29-968f-e255a0efdb33.png)

## Acceptance criteria

INPUT
- [ ] The page shows a form with 6 questions
- [ ] The form shows question for 1. which menstruation products are mostly used
- [ ] The form accepts choices for: tampons, pad, cup, disc, none
- [ ] The form shows question for 2. how many products are in one package (only for tampon and pad)
- [ ] The form accepts answer for 1  to 50
- [ ] The form shows question for 3. costs of one package
- [ ] The form accepts all amounts
- [ ] The form shows question for 4. how much taxes are included in one package
- [ ] The form accepts amounts from 0 to 25 
- [ ] The form shows question for 5. possible tax reduction?
- [ ] The form accepts "keine Steuer, Teilsteuer, volle Steuer" 
- [ ] The form shows questions for 6. how often the product is changed per day (only when tampon or pad is selected)
- [ ] The form accepts amounts from 1 to 10 

OUTPUT
- [ ] The input values are used to calculate the output 
- [ ] The first output shows 1. the mainly used menstruation product and the amount of money you pay 2. per period, 3. per period-year, 4. in a menstruation-life, 5. until today (2.-5. with the according amount of taxes).
- [ ] The page shows an infobox with the content "In Periotopia gäbe es keine finanziellen Hürden und Menstruationsprodukte wären frei zugänglich. Nur in wenigen Ländern ist das schon heute der Fall. In anderen Ländern sind die Produkte von der Steuer befreit oder, wie in Deutschland, zumindest reduziert"
- [ ] The page shows a "Periotopia-Index"
- [ ] The index is beeing calculated: free = 100%, no tax = 75%, reduced tax = 25%, full tax = 0%
- [ ] The index is visible on the page
- [ ] To get a calculated answer, all questions must be answered
- [ ] When a question is not answered an alert appears with the hint, that all fields must be filled out

## Tasks

- [ ] Create a branch
- [ ] Create `FinancialIssuesComponent`
- [ ] Create form for financial issues
- [ ] Render `FinancialIssuesComponent`
- [ ] Use existing components for new questions
- [ ] Make all answers mandatory and create `alert` if that is not the case 
- [ ] Create function to calculate results of the answer
- [ ] Create `IndexComponent`
- [ ] Create function to calculate the `PeriotopiaIndex`
- [ ] Render `IndexComponent`

**Comment by MonaHer** [comment]
LGTM :)
