### ISSUE TITLE
US 12: Add buttons for averages

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#22]
## Value proposition

As a user 
I want to have the possibility to use averages for some answers
So that I can do the questionnaires even if I don't exactly know which numbers to use 

## Description

![Image](https://user-images.githubusercontent.com/132840529/255588090-84f321c4-cae2-41a1-94d6-aee1c71ec0a8.png)

## Acceptance criteria

- [ ] The following questions have an average-button
- [ ] general: Q2: 13 / Q3: 28 / Q4: 5
- [ ] money: Q1: Tampon / Q2: 4,95 (also setting Q5: 64) / Q3: reduced / Q4: 7 / Q6: 4
- [ ] When clicking the buttons, it sets an average to the belonging input-field

## Tasks

- [ ] Create average-Button Component
- [ ] Create function for setting the average
- [ ] Implement button into components
