### ISSUE TITLE
US 12: Add styling

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#25]
## Value proposition

As a user
I want to experience an enhanced design and visually appealing user interface
so that I have a pleasant and intuitive user experience.

## Description

![Image](https://user-images.githubusercontent.com/132840529/256174340-842bd65b-55fd-4c28-b5b3-3011ee2a6b3f.png)

## Acceptance criteria

- [ ] The app has a new design which is modern, aesthetically pleasing and suits the issue of the app (menstruation).
- [ ] There is a consistent use of color palettes and fonts to ensure a cohesive visual appearance throughout all questionnaire-pages (main-colors: redish, pinkish, purple etc. and suitable highlight-colors).
- [ ] The user interface is user-friendly and intuitive, especially concerning interactions with the app.

## Tasks

- [ ] Choose general design for the app to display the questionnaires and results
- [ ] Choose a color palette
- [ ] Adjust color palette to all pages and components
- [ ] Check for user-friendly and intuitive icon- and button use and adjust if necessary

**Comment by FlorianNova** [comment]
I tried it but unfortunately I can't give any positive feedback on this, maybe a woman / girl who is familiar with the topic and sees and understands a possible sense in it should deal with it!

**Comment by tejue** [comment]
@FlorianNova, it would be nice if you could specify your comment. Unfortunately right now, I have no idea what to change in this US so it will be more concrete/understandable (other than just posting it again and hope for someone else to review it).
