### ISSUE TITLE
US 14: Create Intro-Questionnaire

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#26]
## Value proposition

As a non-menstruating user
I want to be welcomed to this app as well
So that I  know how I can use the app even when I am not menstruating

## Description

![Image](https://user-images.githubusercontent.com/132840529/256182668-413f8197-f8e0-44e6-9e0f-8f448e097f07.png)

## Acceptance criteria

- [ ] The app has an intro-questionnaire asking if menstruating with answer-possibilities yes and no
- [ ] When clicking no, a text appers, telling the user how to deal with the app (using averages or asking friends)

## Tasks

- [ ] Implement a short questionnaire
- [ ] Make text visible when clicking no

**Comment by MonaHer** [comment]
LGTM :) 🌼
