### ISSUE TITLE
US 15: Implement cancel-icon

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#27]
## Value proposition

As a user
I want a to see a cancel-icon after each questionnaire-answer
So that I can easily quit the question-round in case I want to stop

## Description

![Image](https://user-images.githubusercontent.com/132840529/256186264-a2edd876-a146-45a2-a6f4-250dab00cb21.png)

## Acceptance criteria

- [ ] The answer-sections of each questionnaire show an icon to cancel the round
- [ ] When clicking on the icon, the user is lead to the main-side of the app (periotopia-index)
- [ ] A new index-box is visible, containing only the results that were answered till cancel

## Tasks

- [ ] Choose icon for canceling
- [ ] Implement cancel-icon on every page, showing the result of the previous answered questions
- [ ] Create function that renders only the answered questions

**Comment by MonaHer** [comment]
LGTM :) 🌷
