### ISSUE TITLE
US 3: Show Infobox with further information

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#3]
## Value proposition

As a user
I want to see a form with the questions 'about you' (me) with corresponding answer possibilities
So that I get an answer of how many days per year/lifetime I am menstruating

## Description

![Image](https://user-images.githubusercontent.com/132840529/251366106-17baa352-b69c-4f29-968f-e255a0efdb33.png)

## Acceptance criteria

INPUT
- [ ] The page shows a form with 4 questions
- [ ] The form shows question for 1. actual age
- [ ] The form accepts age from 8 to 100 
- [ ] The form shows question for 2. age of first menstruation
- [ ] The form accepts age from 7 to 99
- [ ] The form shows question for 3. how often menstruation starts (every...days)
- [ ] The form accepts days from 1 to 60
- [ ] The form shows question for 4. how long menstruation lasts
- [ ] The form accepts days from 1 to 15
- [ ] To see the summary of the answers, a submit button can be clicked

OUTPUT
- [ ] The input values are used to calculate the output 
- [ ] The first output shows the amount of menstruation days within one year, wrapped in the sentence "An (amount) Tagen im Jahr menstruierst du".
- [ ] The page shows an infotext with the content "Auch in Periotopia würdest du menstruieren. Ein paar Dinge wären aber anders..."
- [ ] The second output shows 1. the mainly used menstruation product and the amount of money you pay 2. per period, 3. period-year, 4. in a menstruation-life, 5. until today (2.-5. with the according amount of taxes).
- [ ] The page shows an infotext with the content "Für viele Menschen sind Menstruationsprodukte, auch in Deutschland, finanziell kaum oder nur schwer leistbar. Das Bürgergeld sieht beispielsweise nur 17,14 Euro pro Monat für die gesamte Gesunheitspflege vor."
- [ ] The page shows an infobox with the content "In Periotopia gäbe es keine finanziellen Hürden und Menstruationsprodukte wären frei zugänglich. Nur in wenigen Ländern ist das schon heute der Fall. In anderen Ländern sind die Produkte von der Steuer befreit oder, wie in Deutschland, zumindest reduziert"
- [ ] The page shows a "Periotopia-Index"
- [ ] The index is beeing calculated: free = 100%, no tax = 75%, reduced tax = 25%, full tax = 0%
- [ ] The index is visible on the page
- [ ] To get a calculated answer, all questions must be answered
- [ ] When a question is not answered an alert appears with the hint, that all fields must be filled out
- [ ] The page shows a title

## Tasks

- [ ] Create a branch
- [ ] Create `FormComponent` with a form
- [ ] Render `FormComponent` 
- [ ] Create `QuestionComponent` with questions
- [ ] Render `QuestionComponent` 
- [ ] Make all answers mandatory and create `alert` if that is not the case 
- [ ] Create `SubmitButtonComponent`
- [ ] Create function for submit-button
- [ ] Render `SubmitButtonComponent`
- [ ] Create `IndividuelAnswerComponent` in relation to the answers
- [ ] Create function to calculate results of the answers
- [ ] Render `IndividuelAnswerComponent` in relation to the answers
- [ ] Create `InfoboxComponent` in relation to the answers
- [ ] Create `IndexComponent`
- [ ] Create function to calculate the `index`
- [ ] Render `IndexComponent`
- [ ] Create title for the page
