### ISSUE TITLE
US (DS) 15: Clean code and restructure

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#31]
## Value proposition

As a developer
I want to clean and restructure my code to improve its readability
So that I can make future changes and additions easier.

## Acceptance criteria

- [ ] Unnecessary or redundant code is removed
- [ ] The code doesn't repeat itself
- [ ] Consistent and meaningful naming conventions for variables, functions and styled components are applied

## Tasks

- [ ]  Create a branch
- [ ] Identify and remove redundant code
- [ ] Check all names, if they are semantically correct

**Comment by NilsOt1** [comment]
Awesome!
