### ISSUE TITLE
Split questionblock on separate pages

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#7]
## Value proposition

As a user
I want to switch from one questionnaire to the next 
So that I am not overloaded with to much content on one side

## Acceptance criteria

- [ ] The app has a page `aboutyou`
- [ ] When clicking a button the user is lead to the next page `financials`

## Tasks

- [ ] Create new branch
- [ ] Create new page `financials`
- [ ] Rename old page into `about you`
- [ ] Create link leading from page `aboutyou` to `financials`
- [ ] Make sure everything still works as supposed

**Comment by ArnelaKapllani** [comment]
Hi @tejue 🤗
Is this little arrow the button that will navigate to the next page?
If so, I think it's 👍

**Comment by tejue** [comment]
It is 🤗
