### ISSUE TITLE
Show periotopia-index on overview page

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#8]
## Value proposition

As a user
I want to see my result from the questionnaire on the overview page
So that I see the result in a glance without clicking through pages

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] At the end of the questionnaire you can save your result
- [ ] The result of the periotopia-index is visible on the `overview`page

## Tasks

- [ ] Create a new branch
- [ ] Create a `button` to save the result
- [ ] Implement use `localStorage`
- [ ] Render the periotopia-index on the `overview` page

**Comment by DErdmann1** [comment]
Your US looks good to me 🥳  Not necessary, but u could add an example at your wireframe. 
#goteresa
