### ISSUE TITLE
US 7: Add new questionnaire "Hygiene"

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-periotopia#9]
## Value proposition

As a user
I want to see some questions for 'hygiene' as well as answer possibilities
So that I know how how much time I spend for menstruation-hygiene

## Description

![Image](https://user-images.githubusercontent.com/132840529/253310403-995f8655-1fb4-444c-bd58-4fcb117a9ef3.png)

## Acceptance criteria

- [ ] A new page `Hygiene` is visible and reachable

INPUT
- [ ] The page shows a form with 2 questions
- [ ] The form shows question for 1. access to clean and save sanitation to change products
- [ ] The form accepts choices for: yes and no
- [ ] The form shows question for 2. how long to access
- [ ] It is disabled when question 1 = no
- [ ] The form accepts answer for: from 1 to 30 minutes 

OUTPUT
- [ ] The input values are used to calculate the output 
- [ ] The first output shows the minutes spent to access sanitation (way forth and back) 1. per year, 2. till now, in life
- [ ] The page shows an infobox with the content "In Periotopia hätten alle Menschen freien Zugang zu sauberen und sicheren Sanitären Anlagen"
- [ ] The page shows a "Periotopia-Index"
- [ ] The index is beeing calculated: 1 minute = 100%, no acces = 0%
- [ ] To get a calculated answer, all questions must be answered

## Tasks

- [ ] Create a branch
- [ ] Create page `hygiene`
- [ ] Create `form` for hygiene
- [ ] Render `form`
- [ ] Use existing components for new questions
- [ ] Make all answers mandatory 
- [ ] Create function to calculate results of the answer
- [ ] Calculate index
- [ ] Render index-result in `overview` page
- [ ] Calculate avarege of index-results

**Comment by NilsOt1** [comment]
Just a small typo in the value proposition. Double "how". Apart from that, looks good to me!
